language: c

compiler: clang

sudo: required
dist: trusty

before_script:
 - mkdir -p $HOME/.ccnx/dependencies/download
 - mkdir -p $HOME/.ccnx/distillery
 - echo "DISTILLERY_DEPENDENCIES_DIR=$HOME/.ccnx/dependencies" > $HOME/.ccnx/distillery/config.mk
 - echo "DISABLE_UBUNTU_CHECK=True" >> $HOME/.ccnx/distillery/config.mk
 - echo "MAKE_BUILD_FLAGS=-j1" >> $HOME/.ccnx/distillery/config.mk
 - echo "CMAKE_MAKE_TEST_ARGS=" >> $HOME/.ccnx/distillery/config.mk
 - echo "CMAKE_BUILD_TYPE_FLAG=-DCMAKE_BUILD_TYPE=DEBUG" >> $HOME/.ccnx/distillery/config.mk
 - cat $HOME/.ccnx/distillery/config.mk
 - make info
 - make update

script: 
 - make LongBow Libparc Libparc.check

cache:
  directories:
    - src
    - $HOME/.ccnx

after_failure:
  - pwd
  - ls
  - ./build/Libparc/parc/algol/test/test_parc_Network
  - echo LONGBOW =========================================
  - cat build/LongBow/Testing/Temporary/LastTest.log.tmp
  - echo LIBPARC =========================================
  - cat build/Libparc/Testing/Temporary/LastTest.log.tmp
  - echo LIBCCNX_COMMON =========================================
  - cat build/Libccnx-common/Testing/Temporary/LastTest.log.tmp
