language: c

before_script:
 - mkdir -p $HOME/.ccnx/dependencies
 - DISTILLERY_DEPENDENCIES_DIR=$HOME/.ccnx/dependencies make dependencies
 - DISTILLERY_DEPENDENCIES_DIR=$HOME/.ccnx/dependencies make update

script: DISTILLERY_DEPENDENCIES_DIR=$HOME/.ccnx/dependencies make all check

cache:
  directories:
    - src
    - $HOME/.ccnx
