language: c

before_script:
 - mkdir -p $HOME/.ccnx/dependencies/download
 - mkdir -p $HOME/.ccnx/distillery
 - echo "DISTILLERY_DEPENDENCIES_DIR=$HOME/.ccnx/dependencies" > $HOME/.ccnx/distillery/config.mk
 - echo "DISABLE_UBUNTU_CHECK=True" >> $HOME/.ccnx/distillery/config.mk
 - echo "MAKE_BUILD_FLAGS=-j1" >> $HOME/.ccnx/distillery/config.mk
 - echo "CMAKE_MAKE_TEST_ARGS=" >> $HOME/.ccnx/distillery/config.mk
 - cat $HOME/.ccnx/distillery/config.mk
 - make info
 - make -C dependencies cmake

script: CTEST_OUTPUT_ON_FAILURE=1 make all check

cache:
  directories:
    - src
    - $HOME/.ccnx

after_failure:
  - echo LONGBOW =========================================
  - cat build/LongBow/Testing/Temporary/LastTest.log.tmp
  - echo LIBPARC =========================================
  - cat build/Libparc/Testing/Temporary/LastTest.log.tmp
  - echo LIBCCNX_COMMON =========================================
  - cat build/Libccnx-common/Testing/Temporary/LastTest.log.tmp
